[package]
name = "scotland2_rs"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
crate-type = ["lib", "cdylib"]

[workspace]
members = ["example"]

[build-dependencies]
bindgen = { version = "0.71", default-features = false }
